[2023-05-13T10:44:10.030+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-12T08:16:24.419720+00:00 [queued]>
[2023-05-13T10:44:10.039+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-12T08:16:24.419720+00:00 [queued]>
[2023-05-13T10:44:10.039+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-13T10:44:10.057+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-12 08:16:24.419720+00:00
[2023-05-13T10:44:10.062+0530] {standard_task_runner.py:57} INFO - Started process 10403 to run task
[2023-05-13T10:44:10.068+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'read_and_send_task', 'manual__2023-05-12T08:16:24.419720+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmplvx2eetz']
[2023-05-13T10:44:10.069+0530] {standard_task_runner.py:85} INFO - Job 171: Subtask read_and_send_task
[2023-05-13T10:44:10.124+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-12T08:16:24.419720+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-13T10:44:10.199+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T08:16:24.419720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-12T08:16:24.419720+00:00'
[2023-05-13T10:44:10.470+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-13T10:44:10.470+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-13T10:44:10.471+0530] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2023-05-13T10:44:10.471+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-05-13T10:44:10.520+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-13T10:44:10.520+0530] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2023-05-13T10:44:10.520+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-05-13T10:44:10.521+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test1.py", line 31, in read_from_mongodb_and_send_to_kafka
    producer = KafkaProducer(bootstrap_servers=kafka_bootstrap_servers)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-05-13T10:44:10.527+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_kafka_and_consumer, task_id=read_and_send_task, execution_date=20230512T081624, start_date=20230513T051410, end_date=20230513T051410
[2023-05-13T10:44:10.541+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 171 for task read_and_send_task (NoBrokersAvailable; 10403)
[2023-05-13T10:44:10.559+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T10:44:10.582+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
