[2023-05-19T12:16:59.624+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.submit_topology manual__2023-05-19T06:44:22.071709+00:00 [queued]>
[2023-05-19T12:16:59.632+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.submit_topology manual__2023-05-19T06:44:22.071709+00:00 [queued]>
[2023-05-19T12:16:59.632+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-19T12:16:59.649+0530] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): submit_topology> on 2023-05-19 06:44:22.071709+00:00
[2023-05-19T12:16:59.653+0530] {standard_task_runner.py:57} INFO - Started process 17636 to run task
[2023-05-19T12:16:59.658+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'submit_topology', 'manual__2023-05-19T06:44:22.071709+00:00', '--job-id', '730', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmppl1ydrtq']
[2023-05-19T12:16:59.659+0530] {standard_task_runner.py:85} INFO - Job 730: Subtask submit_topology
[2023-05-19T12:16:59.711+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.submit_topology manual__2023-05-19T06:44:22.071709+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-19T12:16:59.780+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='submit_topology' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T06:44:22.071709+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-19T06:44:22.071709+00:00'
[2023-05-19T12:16:59.782+0530] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-19T12:16:59.783+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/nizam/project/Kafka-Storm && sparse run --name first_topology']
[2023-05-19T12:16:59.794+0530] {subprocess.py:86} INFO - Output:
[2023-05-19T12:17:00.856+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 17636. PIDs of all processes in the group: [17637, 17638, 17639, 17636]
[2023-05-19T12:17:00.856+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 17636
[2023-05-19T12:17:00.857+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-19T12:17:00.857+0530] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-05-19T12:17:00.869+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-19T12:17:00.875+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_kafka_and_consumer, task_id=submit_topology, execution_date=20230519T064422, start_date=20230519T064659, end_date=20230519T064700
[2023-05-19T12:17:00.891+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 730 for task submit_topology (Task received SIGTERM signal; 17636)
