[2023-06-08T14:20:18.965+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: storm_topoo.run_hdfsread_task manual__2023-06-08T08:49:59.773896+00:00 [queued]>
[2023-06-08T14:20:18.983+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: storm_topoo.run_hdfsread_task manual__2023-06-08T08:49:59.773896+00:00 [queued]>
[2023-06-08T14:20:18.984+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-06-08T14:20:19.010+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_hdfsread_task> on 2023-06-08 08:49:59.773896+00:00
[2023-06-08T14:20:19.017+0530] {standard_task_runner.py:57} INFO - Started process 15667 to run task
[2023-06-08T14:20:19.025+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'storm_topoo', 'run_hdfsread_task', 'manual__2023-06-08T08:49:59.773896+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpc2owrsqg']
[2023-06-08T14:20:19.027+0530] {standard_task_runner.py:85} INFO - Job 816: Subtask run_hdfsread_task
[2023-06-08T14:20:19.109+0530] {task_command.py:410} INFO - Running <TaskInstance: storm_topoo.run_hdfsread_task manual__2023-06-08T08:49:59.773896+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-06-08T14:20:19.281+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='storm_topoo' AIRFLOW_CTX_TASK_ID='run_hdfsread_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T08:49:59.773896+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-08T08:49:59.773896+00:00'
[2023-06-08T14:20:19.284+0530] {python.py:183} INFO - Done. Returned value was: None
[2023-06-08T14:20:19.293+0530] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=storm_topoo, task_id=run_hdfsread_task, execution_date=20230608T084959, start_date=20230608T085018, end_date=20230608T085019
[2023-06-08T14:20:19.294+0530] {taskinstance.py:1604} ERROR - Error when executing send_email_notification callback
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1601, in _run_finished_callback
    callback(context)
TypeError: send_email_notification() takes 0 positional arguments but 1 was given
[2023-06-08T14:20:19.358+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-06-08T14:20:19.388+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
