[2023-05-19T12:08:20.685+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: concurrent_bash_tasks.kafkamongo manual__2023-05-19T06:36:01.988167+00:00 [queued]>
[2023-05-19T12:08:20.692+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: concurrent_bash_tasks.kafkamongo manual__2023-05-19T06:36:01.988167+00:00 [queued]>
[2023-05-19T12:08:20.693+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-19T12:08:20.709+0530] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): kafkamongo> on 2023-05-19 06:36:01.988167+00:00
[2023-05-19T12:08:20.712+0530] {standard_task_runner.py:57} INFO - Started process 17064 to run task
[2023-05-19T12:08:20.716+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'concurrent_bash_tasks', 'kafkamongo', 'manual__2023-05-19T06:36:01.988167+00:00', '--job-id', '722', '--raw', '--subdir', 'DAGS_FOLDER/kafkastorm.py', '--cfg-path', '/tmp/tmp7zv0byzc']
[2023-05-19T12:08:20.719+0530] {standard_task_runner.py:85} INFO - Job 722: Subtask kafkamongo
[2023-05-19T12:08:20.762+0530] {task_command.py:410} INFO - Running <TaskInstance: concurrent_bash_tasks.kafkamongo manual__2023-05-19T06:36:01.988167+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-19T12:08:20.837+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='concurrent_bash_tasks' AIRFLOW_CTX_TASK_ID='kafkamongo' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T06:36:01.988167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-19T06:36:01.988167+00:00'
[2023-05-19T12:08:20.838+0530] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-19T12:08:20.839+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/nizam/project/Kafka-Storm/Necessary_Scripts/producer.py']
[2023-05-19T12:08:20.848+0530] {subprocess.py:86} INFO - Output:
[2023-05-19T12:08:20.871+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-05-19T12:08:20.871+0530] {subprocess.py:93} INFO -   File "/home/nizam/project/Kafka-Storm/Necessary_Scripts/producer.py", line 1, in <module>
[2023-05-19T12:08:20.871+0530] {subprocess.py:93} INFO -     from faker import Faker
[2023-05-19T12:08:20.872+0530] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'faker'
[2023-05-19T12:08:20.874+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-19T12:08:20.883+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-19T12:08:20.886+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=concurrent_bash_tasks, task_id=kafkamongo, execution_date=20230519T063601, start_date=20230519T063820, end_date=20230519T063820
[2023-05-19T12:08:20.899+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 722 for task kafkamongo (Bash command failed. The command returned a non-zero exit code 1.; 17064)
[2023-05-19T12:08:20.927+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-19T12:08:20.954+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
