[2023-05-19T16:05:03.866+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: combined_dag.read_and_send_task scheduled__2023-05-15T00:10:00+00:00 [queued]>
[2023-05-19T16:05:03.875+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: combined_dag.read_and_send_task scheduled__2023-05-15T00:10:00+00:00 [queued]>
[2023-05-19T16:05:03.875+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-19T16:05:03.890+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-15 00:10:00+00:00
[2023-05-19T16:05:03.894+0530] {standard_task_runner.py:57} INFO - Started process 25547 to run task
[2023-05-19T16:05:03.899+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'combined_dag', 'read_and_send_task', 'scheduled__2023-05-15T00:10:00+00:00', '--job-id', '746', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkdj80i1c']
[2023-05-19T16:05:03.900+0530] {standard_task_runner.py:85} INFO - Job 746: Subtask read_and_send_task
[2023-05-19T16:05:03.952+0530] {task_command.py:410} INFO - Running <TaskInstance: combined_dag.read_and_send_task scheduled__2023-05-15T00:10:00+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-19T16:05:04.030+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='combined_dag' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-15T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-15T00:10:00+00:00'
[2023-05-19T16:05:04.151+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-19T16:05:04.152+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-19T16:05:04.152+0530] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-19T16:05:04.262+0530] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-05-19T16:05:04.263+0530] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-05-19T16:05:08.776+0530] {conn.py:380} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-19T16:05:08.777+0530] {conn.py:410} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-19T16:05:08.778+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2023-05-19T16:05:52.042+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 25547. PIDs of all processes in the group: [25547]
[2023-05-19T16:05:52.043+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 25547
[2023-05-19T16:05:52.043+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-19T16:05:52.056+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/dag.py", line 55, in read_from_mongodb_and_send_to_kafka
    time.sleep(1)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-19T16:05:52.061+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=combined_dag, task_id=read_and_send_task, execution_date=20230515T001000, start_date=20230519T103503, end_date=20230519T103552
[2023-05-19T16:05:52.081+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 746 for task read_and_send_task (Task received SIGTERM signal; 25547)
[2023-05-19T16:05:52.095+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=25547, status='terminated', exitcode=1, started='16:05:03') (25547) terminated with exit code 1
