[2023-05-17T10:57:08.650+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T05:27:04.394520+00:00 [queued]>
[2023-05-17T10:57:08.662+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T05:27:04.394520+00:00 [queued]>
[2023-05-17T10:57:08.662+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-17T10:57:08.686+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-17 05:27:04.394520+00:00
[2023-05-17T10:57:08.691+0530] {standard_task_runner.py:57} INFO - Started process 7576 to run task
[2023-05-17T10:57:08.695+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'read_and_send_task', 'manual__2023-05-17T05:27:04.394520+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmpgt9phclg']
[2023-05-17T10:57:08.696+0530] {standard_task_runner.py:85} INFO - Job 299: Subtask read_and_send_task
[2023-05-17T10:57:08.749+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T05:27:04.394520+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-17T10:57:08.833+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-17T05:27:04.394520+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-17T05:27:04.394520+00:00'
[2023-05-17T10:57:09.047+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-17T10:57:09.047+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-17T10:57:09.052+0530] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-17T10:57:09.169+0530] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-05-17T10:57:09.170+0530] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-05-17T10:58:50.601+0530] {conn.py:380} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-17T10:58:50.602+0530] {conn.py:410} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-17T10:58:50.602+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2023-05-17T11:02:28.284+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 7576. PIDs of all processes in the group: [7576]
[2023-05-17T11:02:28.284+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 7576
[2023-05-17T11:02:28.285+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-17T11:02:28.293+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test1.py", line 39, in read_from_mongodb_and_send_to_kafka
    for document in cursor:
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1330, in _run_operation
    return self._retryable_read(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1448, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1326, in _cmd
    return server.run_operation(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/server.py", line 115, in run_operation
    reply = sock_info.receive_message(request_id)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/pool.py", line 821, in receive_message
    self._raise_connection_failure(error)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/pool.py", line 819, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-17T11:02:28.303+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_kafka_and_consumer, task_id=read_and_send_task, execution_date=20230517T052704, start_date=20230517T052708, end_date=20230517T053228
[2023-05-17T11:02:28.318+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 299 for task read_and_send_task (Task received SIGTERM signal; 7576)
[2023-05-17T11:02:28.337+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=7576, status='terminated', exitcode=1, started='10:57:08') (7576) terminated with exit code 1
